- 1.10/dind/Dockerfile
- 1.11-rc/dind/Dockerfile
- 1.9/dind/Dockerfile
As much as we can support `devicemapper`, that is -- it still requires `--storage-opt dm.override_udev_sync_check=true` due to our static binary.
Fixes #8
> Add more packages to "dind" for proper "devicemapper" support

- 1.12/Dockerfile
so it is consistent with other env vars
> brackets added to DOCKER_VERSION env var

- .travis.yml
- 1.12/experimental/Dockerfile
- 1.12/experimental/dind/Dockerfile
- 1.12/experimental/dind/dockerd-entrypoint.sh
- 1.12/experimental/docker-entrypoint.sh
- 1.12/experimental/git/Dockerfile
- generate-stackbrew-library.sh
- update.sh
Closes #21
```diff
commit eb714a73e7e3f87705f468c3c6e9f4e316136bf5
Author: Tianon Gravi <admwiggin@gmail.com>
Date:   Mon Aug 22 12:06:09 2016 -0700
Add new "experimental" variant now that 1.12+ has official "experimental" releases
diff --git a/.travis.yml b/.travis.yml
index cf4accc..c49c7e7 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,8 +2,9 @@ language: bash
services: docker
env:
-  - VERSION=1.12
-  - VERSION=1.11
+  - VERSION=1.12 VARIANT=
+  - VERSION=1.12 VARIANT=experimental
+  - VERSION=1.11 VARIANT=
install:
- git clone https://github.com/docker-library/official-images.git ~/official-images
diff --git a/1.12/Dockerfile b/1.12/experimental/Dockerfile
similarity index 79%
copy from 1.12/Dockerfile
copy to 1.12/experimental/Dockerfile
index 4764465..0852d0b 100644
--- …
```
> Add new "experimental" variant now that 1.12+ has official "experimental" releases

- 1.12/dind/dockerd-entrypoint.sh
- 1.12/experimental/dind/dockerd-entrypoint.sh
- 1.13-rc/dind/dockerd-entrypoint.sh
This is going to be especially important for 1.13+ where `docker daemon` is now officially deprecated (and in at least `-rc1`, appears to have issues: https://github.com/docker/docker/issues/28368).
> Convert over to invoking "dockerd" directly instead of relying on the "docker daemon" translation

- 1.11/docker-entrypoint.sh
- 1.12/docker-entrypoint.sh
- 1.13-rc/docker-entrypoint.sh
As per https://github.com/docker/docker/pull/28773 `docker foo --help` will no longer exit with status code 1 anymore, making the entrypoint think that *everything* is a valid docker subcommand.
Note that this will only work with 1.13-rc3 upwards, which is also why tests fail.
> Change `foo --help` check to `help foo` in 1.13 entrypoint

- 1.11/Dockerfile
- 1.12/Dockerfile
- 1.12/experimental/Dockerfile
Fixes #36
See https://github.com/docker-library/golang/pull/131#issuecomment-270677556 for further discussion.
> Revert Alpine 3.5 upgrade in 1.11 and 1.12 (leaving 1.13 on Alpine 3.5)

- 17.03/Dockerfile
- 17.04/Dockerfile
- 17.05-rc/Dockerfile
- update.sh
This allows for the same source to build on both amd64 and armhf -- I'm not 100% sure whether Docker's static binary releases are ARMv6 or ARMv7, and I've only got an ARMv7 environment to test in. :innocent:
Here's some `docker version` and `docker info` output from a running instance of this DinD on an ARM machine:
```console
$ docker -H tcp://172.17.0.2:2375 version
Client:
Version:      1.12.6
API version:  1.24
Go version:   go1.6.2
Git commit:   78d1802
Built:        Tue Jan 31 23:35:09 2017
OS/Arch:      linux/arm
Server:
Version:      17.03.1-ce
API version:  1.27
Go version:   go1.7.5
Git commit:   c6d412e
Built:        Tue Mar 28 03:25:54 2017
OS/Arch:      linux/arm
$ docker -H tcp://172.17.0.2:2375 info
Containers: 0
Running: 0
Paused: 0
Stopped: 0
Images: 0
Server Version: …
```
> Add experimental armhf support via "case" on "apk --print-arch"

- 17.03/Dockerfile
- 17.03/dind/Dockerfile
- 17.05/Dockerfile
- 17.05/dind/Dockerfile
- update.sh
> Switch from get.docker.com to download.docker.com

- .architectures-lib
- 17.03-rc/Dockerfile
- 17.03-rc/release-architectures
- 17.03/Dockerfile
- 17.03/release-architectures
- 17.05/Dockerfile
- 17.05/release-architectures
- 17.06-rc/release-architectures
- Dockerfile-dind.template
- Dockerfile-git.template
- Dockerfile.template
- docker-entrypoint.sh
- dockerd-entrypoint.sh
- generate-stackbrew-library.sh
- update.sh
See also https://github.com/docker-library/buildpack-deps/pull/59 and https://github.com/docker-library/golang/pull/163.
> Add multiarch support (again) and update to 17.06.0-ce-rc2

- 17.03-rc/docker-entrypoint.sh
- 17.03/docker-entrypoint.sh
- 17.05/docker-entrypoint.sh
- 17.06-rc/docker-entrypoint.sh
- docker-entrypoint.sh
Fixes #61
Here's the example output:
```console
$ docker run -it --rm docker:17.06-rc dockerd
📎 Hey there!  It looks like you're trying to run a Docker daemon.
You probably should use the "dind" image variant instead, something like:
docker run --privileged --name some-overlay-docker -d docker:stable-dind --storage-driver=overlay
See https://hub.docker.com/_/docker/ for more documentation and usage examples.
WARN[0000] could not change group /var/run/docker.sock to docker: group docker not found
...
```
> Add a little "paperclip" suggestion when attempting to run "dockerd" in the non-dind image variants

- 17.06/Dockerfile
- 17.07/Dockerfile
- 17.09/Dockerfile
- 17.10-rc/Dockerfile
- Dockerfile.template
> Add bare-bones "/etc/nsswitch.conf" for "netgo" to know it should check "/etc/hosts" before doing DNS lookups

- 17.06/dind/Dockerfile
- 17.09/dind/Dockerfile
- 17.10/dind/Dockerfile
- Dockerfile-dind.template
Like it says on the tin. Without the zfs binaries included, the `:dind` images fail when Docker uses the zfs graph driver. If there are compatibility issues with adding the zfs package to every image, please let me know.
Here is what I have to do to get GitLab CI to work with Docker and the zfs graph driver.
1. Create a custom `:dind` image:
https://gitlab.frielforreal.com/global/docker/blob/master/dind/Dockerfile:
```dockerfile
FROM docker:dind
RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
zfs
COPY dind-entrypoint.sh /usr/local/bin/
ENTRYPOINT ["dind-entrypoint.sh"]
CMD []
```
2. Modify `.gitlab-ci.yml` to use the above images instead of `docker:dind` and alias it to ` docker`:
https://gitlab.frielforreal.com/global/docker/blob/master/.gitlab-ci.yml …
> Add zfs progs to :dind images

- 17.06/dind/dockerd-entrypoint.sh
- 17.09/dind/dockerd-entrypoint.sh
- 17.10/dind/dockerd-entrypoint.sh
- dockerd-entrypoint.sh
This is a follow-on of #88. The vfs storage driver is no longer defaulted to, as Docker now has more sensible defaults than it did when device mapper was used. Years ago, Docker defaulted to the devicemapper storage driver, which had issues reclaiming space and filling disks (see: moby/moby/issues/3182). I believe the reason the Docker in Docker (`dind`) image defaulted to the vfs storage driver was to avoid that issue.
Fortunately, since I created moby/moby/issues/3182, Docker now defaults to more flexible storage drivers such as overlay2, zfs, and btrfs, and the `dind` image no longer needs to default to vfs.
This PR will improve performance of Docker in Docker images running on any of the aforementioned storage drivers.
> Remove vfs as default storage driver.

- Dockerfile-dind.template
- update.sh
Docker 18.02 will us parallel decompression of images after pulling, but relies on the `pigz` binary to be present.
This patch adds the pigz binary :)
relates to https://github.com/moby/moby/pull/35697
> Add pigz binary for upcoming Docker 18.02 release

- 17.12/dind/dockerd-entrypoint.sh
- 18.03/dind/dockerd-entrypoint.sh
- 18.04-rc/dind/dockerd-entrypoint.sh
- dockerd-entrypoint.sh
> Explicitly remove "/var/run/docker.pid" at container startup (in case Docker didn't stop cleanly)

- 17.12/dind/Dockerfile
- 18.03/dind/Dockerfile
- 18.04/dind/Dockerfile
- 18.05-rc/dind/Dockerfile
- Dockerfile-dind.template
- update.sh
Users on versions older than 1.8 should probably upgrade at this point.
Using something like `-v /sys/fs/cgroup:/sys/fs/cgroup` on 1.6 and 1.7 is probably the only workaround to this update.
For reference:
```diff
$ GIT_PAGER=cat git diff 3b5fac462d21ca164b3778647420016315289034...52379fa76dee07ca038624d639d9e14f4fb719ff -- hack/dind
diff --git a/hack/dind b/hack/dind
index a8c09283f6..3254f9dbe7 100755
--- a/hack/dind
+++ b/hack/dind
@@ -1,11 +1,11 @@
-#!/bin/bash
+#!/usr/bin/env bash
set -e
#
-# This script should be executed inside a docker container in privilieged mode
+# This script should be executed inside a docker container in privileged mode
@@ -13,74 +13,6 @@ set -e
export container=docker
-# as of docker 1.8, cgroups will be mounted in the container
-if ! mountpoint -q …
```
> Finally update "dind" wrapper to the latest commit

- 18.03/dind/dockerd-entrypoint.sh
- 18.05/dind/dockerd-entrypoint.sh
- 18.06-rc/dind/dockerd-entrypoint.sh
- dockerd-entrypoint.sh
This is the root behind the system failure which caused https://github.com/gliderlabs/docker-alpine/issues/418#issuecomment-403054625.
> Update pid deletion code to also delete "docker-containerd.pid"

- 18.06/Dockerfile
- 18.06/dind/Dockerfile
- 18.09-rc/Dockerfile
- 18.09-rc/dind/Dockerfile
- Dockerfile-dind.template
- Dockerfile.template
Alpine 3.8's `wget` appears to work fine now, and already includes bits necessary for TLS, so this Just Works™ now. :+1:
> Switch back to built-in "wget" (which works now!)

- 18.06/dind/dockerd-entrypoint.sh
- 18.09-rc/dind/dockerd-entrypoint.sh
- 18.09/dind/dockerd-entrypoint.sh
- 19.03-rc/dind/dockerd-entrypoint.sh
- dockerd-entrypoint.sh
This is both more deterministic and makes `shellcheck` happy.
> use absolute path instead of dynamic lookup

- 18.09-rc/docker-entrypoint.sh
- 18.09/docker-entrypoint.sh
- 19.03-rc/docker-entrypoint.sh
- docker-entrypoint.sh
This removes the no-longer-necessary explicit `overlay` override and the no-longer-recommended "stable" tag.
> Use a simpler "dind" example in non-dind images

- 18.09-rc/Dockerfile
- 18.09-rc/dind/Dockerfile
- 18.09-rc/dind/dockerd-entrypoint.sh
- 18.09-rc/docker-entrypoint.sh
- 18.09/Dockerfile
- 18.09/dind/Dockerfile
- 18.09/dind/dockerd-entrypoint.sh
- 18.09/docker-entrypoint.sh
- 19.03-rc/Dockerfile
- 19.03-rc/dind/Dockerfile
- 19.03-rc/dind/dockerd-entrypoint.sh
- 19.03-rc/docker-entrypoint.sh
- Dockerfile-dind.template
- Dockerfile.template
- docker-entrypoint.sh
- dockerd-entrypoint.sh
- update.sh
Closes #164
Refs https://github.com/docker-library/docs/pull/1525
This adds a `DOCKER_TLS_CERTDIR` environment variable that, when present, will auto-enable TLS on `dockerd` by default (and will set the appropriate client flags if the necessary certificates exist).
It will attempt to generate a suitable `subjectAltName` extension value based on all available container IP addresses and hostnames, but the default generation can be extended via the `DOCKER_TLS_SAN` environment variable (in the standard OpenSSL format, ala `IP:n.n.n.n,DNS:foobar,...`).
For users of 18.09 who wish to enable this behavior, simply set `DOCKER_TLS_CERTDIR` to a path within the container into which you want certificates generated (and share at least the `client` subdirectory of that path with your client …
> Add automatic TLS generation (and enable it by default in 19.03+)

- 18.09-rc/Dockerfile
- 18.09-rc/dind/Dockerfile
- 18.09-rc/dind/dockerd-entrypoint.sh
- 18.09-rc/docker-entrypoint.sh
- 18.09/Dockerfile
- 18.09/dind/Dockerfile
- 18.09/dind/dockerd-entrypoint.sh
- 18.09/docker-entrypoint.sh
- 19.03-rc/Dockerfile
- 19.03-rc/dind-rootless/Dockerfile
- 19.03-rc/dind/Dockerfile
- 19.03-rc/dind/dockerd-entrypoint.sh
- 19.03-rc/docker-entrypoint.sh
- 19.03/Dockerfile
- 19.03/dind-rootless/Dockerfile
- 19.03/dind/Dockerfile
- 19.03/dind/dockerd-entrypoint.sh
- 19.03/docker-entrypoint.sh
- Dockerfile-dind-rootless.template
- Dockerfile-dind.template
- Dockerfile.template
- docker-entrypoint.sh
- dockerd-entrypoint.sh
- generate-stackbrew-library.sh
- update.sh
This is an alternative proposal to https://github.com/docker-library/docker/pull/165 + https://github.com/docker-library/docker/pull/168.
This should have roughly the same behavior as the `dockerd-rootless.sh` script but without the extra depdendency (and frankly I'd love to pull some official `vpnkit` release binaries too instead of pulling the extras bundle, but I couldn't find any official binary releases nor did it look trivial to build from source).  This allows us to iterate on this in between Docker releases as well, if necessary (like pulling in a newer `rootlesskit` release, for example).
I was toying with automatically adding `--experimental` as well, but wanted to enforce that being opt-in so that users don't switch without realizing what they're doing (since it does require …
> Add experimental "rootless" dind variant

- 18.09-rc/dind/dockerd-entrypoint.sh
- 18.09/dind/dockerd-entrypoint.sh
- 19.03-rc/dind/dockerd-entrypoint.sh
- 19.03/dind/dockerd-entrypoint.sh
- dockerd-entrypoint.sh
https://github.com/docker-library/docker/pull/174 added an experimental "rootless" variant of the DinD service.
While the change itself is simple and should not affect current usages, a `DOCKER_HOST` variable was used to define which docker.sock path should be used depending on the process owner's ID.
Chosing DOCKER_HOST variable for this is unfortunately not the best option:
1. It's not the best semantic choice - the code that uses it defines a socket file, not the host. DOCKER_SOCKET just seems to fit better the purpose.
1. DOCKER_HOST is already a variable, that is used by users to define where the Docker daemon is listening. In case when it's added to the DinD container (which is a common situation for example for GitLab CI jobs that are using DinD as a service), it finally ends with …
> Rename variable used for defining used docker.sock file

- 18.09-rc/dind/dockerd-entrypoint.sh
- 18.09/dind/dockerd-entrypoint.sh
- 19.03-rc/dind/dockerd-entrypoint.sh
- 19.03/dind/dockerd-entrypoint.sh
- dockerd-entrypoint.sh
The `/usr/local/bin/dind` script is only barely meaningful for the running-as-root case anymore and definitely holds no value for rootless. :+1:
(For repeated context, that script used to be what would set up `/sys/fs/cgroup` inside the container, but Docker itself has been doing so automatically in a reasonable way for a very long time now.)
> Only apply "/usr/local/bin/dind" if we aren't rootless

- 18.09-rc/dind/dockerd-entrypoint.sh
- 18.09/dind/dockerd-entrypoint.sh
- 19.03-rc/dind/dockerd-entrypoint.sh
- 19.03/dind/dockerd-entrypoint.sh
- dockerd-entrypoint.sh
This makes the checks more forgiving (especially for kernels already built with the necessary functionality enabled like AL2) preferring instead to allow Docker itself to fail if the necessary conditions are not met.
Closes #183
cc @benabineri
> Relax "pre-flight" checks for rootless

- 19.03-rc/dind-rootless/Dockerfile
- 19.03/dind-rootless/Dockerfile
- Dockerfile-dind-rootless.template
Corresponds to Docker v19.03.5
https://github.com/docker/engine/blob/v19.03.5/hack/dockerfile/install/rootlesskit.installer
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
> update RootlessKit to v0.7.0

- 19.03-rc/Dockerfile
- 19.03-rc/git/Dockerfile
- 19.03/Dockerfile
- 19.03/git/Dockerfile
- Dockerfile-git.template
- Dockerfile.template
This adds ~6MB (which is nothing compared to the Docker artifacts), and since 19.03.x gives us support for `DOCKER_HOST=ssh://...` (https://github.com/docker/cli/pull/1014)
Closes #206
> Add "openssh-client" to the standard client images

- 19.03-rc/dind-rootless/Dockerfile
- 19.03-rc/dind/dockerd-entrypoint.sh
- 19.03/dind-rootless/Dockerfile
- 19.03/dind/dockerd-entrypoint.sh
- Dockerfile-dind-rootless.template
- dockerd-entrypoint.sh
Also, update entrypoint for a few adjustments made upstream:
- https://github.com/moby/moby/pull/40635: launch rootlesskit with --propagation=rslave
- https://github.com/moby/moby/pull/39840: harden slirp4netns with mount namespace and seccomp
I was going to include https://github.com/moby/moby/pull/40406 as well, but it doesn't appear that https://github.com/moby/moby/commit/3518383ed990202d93e5458782d2c975c48ececd is in the released versions of Docker yet (and the additional argument should be reasonably harmless).
> Update rootlesskit to 0.9.1

- 19.03-rc/dind/dockerd-entrypoint.sh
- 19.03/dind/dockerd-entrypoint.sh
- dockerd-entrypoint.sh
> Specify absolute path to rootlesskit-docker-proxy

- generate-stackbrew-library.sh
This will remove the "test" and "stable" aliases for whatever major release comes after 19.03 (so once the next release comes out, "stable" will become a stale alias).
I'm not 100% sure this is the right answer, but the "stable" alias has definitely been a huge source of confusion very recently (and it doesn't have much meaning anymore anyways given the death of the "edge" channel).
Closes #178
> Restrict channel aliases to 19.03

- 19.03-rc/dind-rootless/Dockerfile
- 19.03/dind-rootless/Dockerfile
- Dockerfile-dind-rootless.template
Fix port forwarder resource leak (https://github.com/rootless-containers/rootlesskit/issues/153).
Other changes: https://github.com/rootless-containers/rootlesskit/releases
> bump up rootlesskit to v0.10.0

- 19.03-rc/dind-rootless/Dockerfile
- 19.03/dind-rootless/Dockerfile
- 20.10-rc/dind-rootless/Dockerfile
- Dockerfile-dind-rootless.template
We were explicit about this previously because the version included with Docker wasn't new enough, and that's no longer the case.
Closes #269 (thanks for the prod, @vicamo!)
> Remove explicit rootlesskit version

- 20.10-rc/dind/Dockerfile
- 20.10/dind/Dockerfile
- Dockerfile-dind.template
Docker 20.10+ now supports ip6tables!
> Add ip6tables in 20.10+

- 19.03-rc/Dockerfile
- 19.03/Dockerfile
- 20.10-rc/Dockerfile
- 20.10/Dockerfile
- versions.json
- versions.sh
This is especially useful for downstream consumers of the DIND images as 3.12 had some quite old packages
Signed-off-by: Martin Rauscher <martin@balena.io>
> update to alpine 3.13

- 20.10/windows/windowsservercore-1809/Dockerfile
- Dockerfile-windows-servercore.template
- Dockerfile.template
- apply-templates.sh
- generate-stackbrew-library.sh
- versions.json
- versions.sh
Hi guys,
I've needed to use docker on windows image and I've noticed the one in the repo is quite a bit old now. 
- So I've updated the windows base image in the template
- and explicitly added windows version based on current ltsc2019.
Do you think it is welcomed change? 
I think the template would deserve the update.
And about the explicite file, I'm not sure if it won't collide with the ci here in the repo.
> Windows update

- 19.03-rc/dind/dockerd-entrypoint.sh
- 19.03/dind/dockerd-entrypoint.sh
- 20.10-rc/dind/dockerd-entrypoint.sh
- 20.10/dind/dockerd-entrypoint.sh
- dockerd-entrypoint.sh
Refs https://github.com/docker-library/docker/issues/318
> Add (hopefully temporary) workaround for containerd-shim zombies

- 20.10/Dockerfile
- Dockerfile.template
When compiling containerd's ctr on Go 1.15 or up, the produced binary
is not fully static, causing it to fail on Alpine:
ldd /usr/local/bin/ctr
/lib64/ld-linux-x86-64.so.2 (0x7f1970417000)
This issue is tracked in containerd/containerd#5824.
Until it's fixed, adding `libc6-compat` as a workaround:
https://pkgs.alpinelinux.org/package/edge/main/x86_64/libc6-compat
Note that there's an alternative `gcompat` package, which provides similar
functionality (and also resolves the issue), but unlike `libc6-compat`, that
package is a `community` package, is larger, and has more dependencies:
https://pkgs.alpinelinux.org/package/edge/community/x86_64/gcompat
Update the Dockerfile with Docker 20.10.8, which is currently on download-stage.docker.com
> add workaround for non-static `ctr` binary in docker 20.10.8

- generate-stackbrew-library.sh
[arm32v6](https://doi-janky.infosiftr.net/job/multiarch/view/images/view/docker/job/arm32v6/job/docker/): still broken
```console
+ bashbrew build docker:20.10.8
...
+ dockerd --version
Bus error (core dumped)
+ bashbrew build docker:19.03.15
...
+ dockerd --version
Segmentation fault (core dumped)
```
[arm32v7](https://doi-janky.infosiftr.net/job/multiarch/view/images/view/docker/job/arm32v7/job/docker/): still broken
```console
+ Bus error docker:20.10.8
...
+ dockerd --version
Illegal instruction (core dumped)
+ bashbrew build docker:19.03.15
...
+ dockerd --version
Segmentation fault (core dumped)
```
ref https://github.com/docker-library/docker/issues/260
closes https://github.com/docker-library/docker/issues/325
cc @thaJeztah anything @tianon and I can do to help debug the upstream …
> Drop arm32v6 and arm32v7 builds for now

- generate-stackbrew-library.sh
This is a prerequisite of something like #317 to ensure users who can't update Docker for one reason or another have an escape hatch (which also means they won't update Docker-in-Docker either, but they can't have everything). ￼:sweat_smile:
<details>
<summary>Diff:</summary>
```diff
$ diff -u <(bashbrew cat docker) <(bashbrew cat <(./generate-stackbrew-library.sh))
--- /dev/fd/63	2021-08-20 16:10:13.849510802 -0700
+++ /dev/fd/62	2021-08-20 16:10:13.849510802 -0700
@@ -1,22 +1,22 @@
Maintainers: Tianon Gravi <tianon@dockerproject.org> (@tianon), Joseph Ferguson <yosifkit@gmail.com> (@yosifkit)
GitRepo: https://github.com/docker-library/docker.git
-Tags: 20.10.8, 20.10, 20, latest
+Tags: 20.10.8, 20.10, 20, latest, 20.10.8-alpine3.13, 20.10-alpine3.13, 20-alpine3.13, alpine3.13 …
```
> Add suite aliases ("alpine3.13")

- 20.10/dind/dockerd-entrypoint.sh
- dockerd-entrypoint.sh
Fixes https://github.com/docker-library/docker/issues/350
Refs https://github.com/moby/moby/issues/26824
> Invoke "modprobe ip_tables" if "iptables -L" fails

- 20.10/Dockerfile
- Dockerfile.template
- versions.json
- versions.sh
- Closes #303
- Closes #355
- Closes https://github.com/docker/roadmap/issues/322
(I don't actually have permission for this to auto-close https://github.com/docker/roadmap/issues/322, so maybe someone like @thaJeztah or @chris-crone can do the honors once we get this in.)
Refs:
- #18
- #30
- #42
- #156
- #243
- #313
- https://github.com/docker/compose/issues/8871
- https://github.com/docker/roadmap/issues/256
- https://github.com/docker/docker-ce-packaging/pull/309
As a warning, this does very severely bloat the size of the Docker images (something like 100MiB more), but given these are part of the "Docker Experience" I think it makes sense. :see_no_evil:
> Add "buildx" and "compose" CLI plugins (for supported architectures of each)

- 20.10/dind-rootless/Dockerfile
- 22.06-rc/dind-rootless/Dockerfile
- Dockerfile-dind-rootless.template
The kernel-mode overlayfs doesn't work with rootless, though Ubuntu and Debian has patched their kernels to enable overlayfs for rootless.
OTOH fuse-overlayfs works with rootless on any distro with kernel >= 4.18.
fuse-overlayfs is supported since Docker 20.10.
https://github.com/moby/moby/issues/40218
> rootless: add fuse-overlayfs

- 20.10/cli/Dockerfile
- 22.06-rc/cli/Dockerfile
- Dockerfile-cli.template
Also update the outdated links :see_no_evil: 
Alpine 3.16 has updated to [include an `nsswitch.conf`](https://git.alpinelinux.org/aports/commit/main/alpine-baselayout?h=3.16-stable&id=348653a9ba0701e8e968b3344e72313a9ef334e4).
```console
$ docker pull alpine:3.16
3.16: Pulling from library/alpine
Digest: sha256:b95359c2505145f16c6aa384f9cc74eeff78eb36d308ca4fd902eeeb0a0b161b
Status: Image is up to date for alpine:3.16
docker.io/library/alpine:3.16
$ docker build 20.10/cli/
Sending build context to Docker daemon  12.29kB
Step 1/15 : FROM alpine:3.16
---> bfe296a52501
Step 2/15 : RUN apk add --no-cache 		ca-certificates 		libc6-compat 		openssh-client
---> Running in cc5019465399
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch …
```
> Swap netgo prep to check instead of create

- 20.10/dind/dockerd-entrypoint.sh
- 23.0/dind/dockerd-entrypoint.sh
- dockerd-entrypoint.sh
If TLS is requested (via `DOCKER_TLS_CERTDIR`) and the directory is not writable, then it should not silently disable TLS.
Fixes https://github.com/docker-library/docker/issues/397
> prevent tls being disabled if _tls_generate_certs fails

- 20.10/dind/dockerd-entrypoint.sh
- 23.0/dind/dockerd-entrypoint.sh
- dockerd-entrypoint.sh
This is the way to specify "I want TLS configured, but I'm managing the certs myself"
The only thing we'll do is verify that the `cert.pem` is legit with respect to the `ca.pem` and then we'll let Docker itself provide any relevant errors beyond that.
Fixes #401
> Adjust DOCKER_TLS_CERTDIR behavior to allow providing server certs without CA

- 20.10/dind/dockerd-entrypoint.sh
- 23.0/dind/dockerd-entrypoint.sh
- dockerd-entrypoint.sh
This fixes the implementation in https://github.com/docker-library/docker/pull/402 to _actually_ work correctly.
Refs https://github.com/docker-library/docker/issues/401
> Fix TLS typo, again, with vigor

- generate-stackbrew-library.sh
```diff
$ diff -u --color <(bashbrew cat docker) <(bashbrew cat <(./generate-stackbrew-library.sh))
--- /dev/fd/63	2023-03-20 14:01:28.524558458 -0700
+++ /dev/fd/62	2023-03-20 14:01:28.516558392 -0700
@@ -1,5 +1,6 @@
Maintainers: Tianon Gravi <tianon@dockerproject.org> (@tianon), Joseph Ferguson <yosifkit@gmail.com> (@yosifkit)
GitRepo: https://github.com/docker-library/docker.git
+Builder: buildkit
Tags: 23.0.1-cli, 23.0-cli, 23-cli, cli, 23.0.1-cli-alpine3.17
Architectures: amd64, arm64v8
@@ -26,6 +27,7 @@
Architectures: windows-amd64
GitCommit: 1497727a0ec70e78a78563f365c76a21749ac27a
Directory: 23.0/windows/windowsservercore-ltsc2022
+Builder: classic
Constraints: windowsservercore-ltsc2022
Tags: 23.0.1-windowsservercore-1809, 23.0-windowsservercore-1809, 23-windowsservercore-1809, …
```
> Opt into buildkit-based builds

- 23.0/git/Dockerfile
- 24-rc/git/Dockerfile
- Dockerfile-git.template
Historically, `docker build git://...` would invoke `git` in the client context, but `buildx` does so in the daemon context instead, and given that it is the default in 23+, let's adjust the git-including variant to be dind-based to simplify this for users who desire the 50MiB+ increase this workflow requires.
Fixes #422
Closes #295
> Swap "git" variant to be "dind"-based in 23+

- 20.10/cli/Dockerfile
- 23.0/cli/Dockerfile
- 24-rc/cli/Dockerfile
- Dockerfile-cli.template
See also https://alpinelinux.org/posts/Alpine-3.18.0-released.html.
> Update to Alpine 3.18

- generate-stackbrew-library.sh
- fixes https://github.com/docker-library/docker/issues/260
- fixes https://github.com/docker-library/docker/issues/325
- updates https://github.com/docker-library/docker/pull/326
- relates to https://github.com/moby/moby/issues/31254#issuecomment-1738675671
Builds for these architectures were broken for some time, but this should be resolved now, so we can re-enable these (fingers crossed).
This reverts commit 461a3ec6ed346995c5949cc2d70c08b9d049caa0.
> re-enable arm32v6 and arm32v7 builds

- 24/cli/Dockerfile
- 24/dind/dockerd-entrypoint.sh
- 25-rc/cli/Dockerfile
- 25-rc/dind/dockerd-entrypoint.sh
- Dockerfile-cli.template
- dockerd-entrypoint.sh
This updates Alpine to the latest stable version: 3.19.
See also https://alpinelinux.org/posts/Alpine-3.19.0-released.html.
*Edit: This is currently blocked as it requires additional upstream support for `nftables`; see also [comment below](https://github.com/docker-library/docker/pull/461#issuecomment-1845922045) and #437.*
Closes: https://github.com/docker-library/docker/pull/437
> Update to Alpine 3.19

- 24/dind/Dockerfile
- 24/dind/dockerd-entrypoint.sh
- 25-rc/dind/Dockerfile
- 25-rc/dind/dockerd-entrypoint.sh
- Dockerfile-dind.template
- dockerd-entrypoint.sh
* Closes #461
* Closes #463
* Related to https://gitlab.com/gitlab-com/gl-infra/production/-/issues/17283
PR #461 updated Alpine to 3.19 and made a change to load the nf_tables kernel module if needed. However, as demonstrated by #463 and #464 this might break when the host system doesn't have the nf_tables module available. In that case, we should still try to load the ip_tables module and symlink /sbin/iptables to xtables-legacy-multi.
> Switch over to xtables-legacy when nf_tables module isn't available

- 24/cli/Dockerfile
- 25-rc/cli/Dockerfile
- Dockerfile-cli.template
This reverts commit 3a0424834732f20142291cdd1d392e6d860af2ad (which reverted commit 9ebd7f6d5a3f26f47d627d0d7510f4b05fc9e977).
See #462 and https://github.com/docker-library/official-images/pull/15943, especially https://github.com/docker-library/official-images/pull/15943#issuecomment-1866962674
> Add a "docker" group (take two)

- 24/dind/dockerd-entrypoint.sh
- 25-rc/dind/dockerd-entrypoint.sh
- dockerd-entrypoint.sh
The nature of `modprobe` in this image is that it works via `ip` hacks, but the exit code will always be non-zero because we don't have `/lib/modules` from the host.
The effect of this was that everyone was using `iptables-legacy` (whether it was warranted for them to be doing so or not).
This probably fixes #466
This probably also fixes #467
> Ignore the exit code of `modprobe` always

- versions.sh
For some reason, `curl -L https://github.com/docker/docker/commits/master/hack/dind.atom` has recently changed from returning XML by default to returning JSON, which from https://docs.github.com/en/rest/activity/feeds?apiVersion=2022-11-28 seems like it's intentional, so this adds an explicit `Accept:` header (the only explicit JSON one that seems to work) and uses `jq` to determine the latest `hack/dind` commit instead of hacking up the XML via `grep`+`awk`.
> Switch to consuming JSON from GitHub for "latest commit"

- 24/dind/Dockerfile
- 24/git/Dockerfile
- 25/dind/Dockerfile
- 25/git/Dockerfile
- Dockerfile-dind.template
- Dockerfile-git.template
- generate-stackbrew-library.sh
- versions.json
- versions.sh
See https://github.com/docker-library/docker/issues/482#issuecomment-1955609423
Closes #482
(with [apologies](https://github.com/docker-library/docker/pull/295) to @thaJeztah :heart:)
This also does some minor cleanup of our installation of other dependencies.
> Add `git` to `dind` variants (and make `git` an alias of `dind`, for 24.x and 25.x)

- versions.sh
This allows the script to differentiate 404 from 503 so that we are less likely to accidentally commit downgrades (like https://github.com/docker-library/docker/commit/9b7730d06c32e4e5521e8a3061bd200a77f2132a) for temporary failures.
Example output if I change the `case` to not match 200 anymore:
```console
$ ./versions.sh
error: unexpected status code 200 while fetching: -H Accept: application/json https://github.com/docker/docker/commits/master/hack/dind.atom
Terminated
$ 
```
> Update "versions" curl invocation to be more defensive

- 24/cli/Dockerfile
- 25/cli/Dockerfile
- 26/cli/Dockerfile
- Dockerfile-cli.template
This updates Alpine to the latest stable version: 3.20.
Requires https://github.com/docker-library/official-images/pull/16801.
See also https://alpinelinux.org/posts/Alpine-3.20.0-released.html.
Modelled after #461 (albeit hopefully less 'impactful' this time 😓)
> Update to Alpine 3.20

- 24/dind/dockerd-entrypoint.sh
- 25/dind/dockerd-entrypoint.sh
- 26/dind/dockerd-entrypoint.sh
- 27-rc/dind/dockerd-entrypoint.sh
- dockerd-entrypoint.sh
This isn't used/necessary in the default configuration until Docker 27+, but it was optional behavior before that, so it's prudent for us to also try loading it any time we know we're not using nftables / have explicitly requested "legacy" `iptables`.
See also:
- https://github.com/moby/moby/pull/47747
- https://github.com/moby/moby/issues/47895
- https://github.com/moby/moby/pull/47918
- https://github.com/moby/moby/pull/47960
cc/fyi @robmry @akerouanton :heart:
> Also load `ip6_tables` when trying to load `ip_tables`

- 24/cli/Dockerfile
- 25/cli/Dockerfile
- 26/cli/Dockerfile
- 27/cli/Dockerfile
- Dockerfile-cli.template
- `docker build .` / `docker buildx build .` might shell out to git to ask about the context directory's `git status`
- `DOCKER_BUILDKIT=0 docker build https://example/foo.git` will run git in the client context
- `docker buildx build https://example/foo.git` will run git in the daemon context
https://github.com/docker-library/docker/issues/482#issuecomment-2197116408
> Add `git` to CLI variants

- versions.sh
Adjust jq regex to account for BSD artifacts
Before the fix:
```console
jq: error (at <stdin>:39): failed to parse os-arch from filename: buildx-v0.19.1.freebsd-amd64
```
After the fix:
```console
$ ./versions.sh
27: 27.3.1 (buildx 0.19.1, compose 2.31.0)
27-rc: 27.4.0-rc.3 (buildx 0.19.1, compose 2.31.0)
```
> Fix failing `versions.sh` that is causing the update job to fail

- 27-rc/cli/Dockerfile
- 27-rc/dind/Dockerfile
- 27/cli/Dockerfile
- 27/dind/Dockerfile
- Dockerfile-cli.template
- Dockerfile-dind.template
Modelled after #498.
Requires https://github.com/docker-library/official-images/pull/18024.
This PR updates Alpine to the latest stable version: 3.21.
See also https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.21.0.
> Update to Alpine 3.21

- 27/windows/windowsservercore-ltsc2025/Dockerfile
- versions.json
- versions.sh
Add Windows Server ltsc2025; keep 1809 as it is still in extended support (we may drop it later, even while it is supported by Windows).
Refs: https://github.com/docker-library/official-images/pull/18143
> Add Windows Server 2025 variant

- versions.sh
Basically, the same as https://github.com/docker-library/docker/pull/516, but now there are `netbsd` artifacts to account for so I made the regex more generic to match any `bsd`.
> Adjust jq regex to account for (more) BSD artifacts

- 28/dind/dockerd-entrypoint.sh
- dockerd-entrypoint.sh
This MR adds some additional extensions to the self-generated CA and server certificates the dind image may employ to set up TLS connections. This ensures the certificates (better) match RFCs specifying these extensions as required (see https://datatracker.ietf.org/doc/html/rfc3280 and https://datatracker.ietf.org/doc/html/rfc5280). This is particularly relevant for clients enforcing checks on this while connecting.
When using my combination of:
- GitLab CI 
- Docker dind image as service in CI job
- Python Docker image employing the [Docker SDK for Python](https://docker-py.readthedocs.io/en/stable/) to connect to the Docker daemon
I was presented with errors among the following lines:
> docker.errors.DockerException: Error while fetching server API version: …
> Add additional extensions to generated ssl certs
