1.7/Dockerfile, 1.8-rc/Dockerfile, 1.8/Dockerfile
This avoids strange intermittent issues like:
```
Connecting to test.docker.com (216.137.36.117:443)
wget: error getting response: Connection reset by peer
```
=> Switch from "wget" to "curl"

1.11/dind/dockerd-entrypoint.sh, 1.11/docker-entrypoint.sh, 1.12-rc/dind/dockerd-entrypoint.sh, 1.12-rc/docker-entrypoint.sh, 1.12-rc/experimental/dind/dockerd-entrypoint.sh, 1.12-rc/experimental/docker-entrypoint.sh, 1.12/dind/dockerd-entrypoint.sh, 1.12/docker-entrypoint.sh, 1.12/experimental/dind/dockerd-entrypoint.sh, 1.12/experimental/docker-entrypoint.sh
=> Improve POSIX compliance of our entrypoint scripts

.travis.yml, 17.06-rc/Dockerfile, 17.06-rc/dind/Dockerfile, 17.06-rc/dind/dockerd-entrypoint.sh, 17.06-rc/docker-entrypoint.sh, 17.06-rc/git/Dockerfile, generate-stackbrew-library.sh, update.sh
https://github.com/docker/docker-ce/releases/tag/v17.06.0-ce-rc1
=> Add 17.06.0-ce-rc1

.travis.yml, 17.03-rc/Dockerfile, 17.03-rc/dind/Dockerfile, 17.03-rc/dind/dockerd-entrypoint.sh, 17.03-rc/docker-entrypoint.sh, 17.03-rc/git/Dockerfile
https://github.com/moby/moby/releases/tag/v17.03.2-ce-rc1
=> Add 17.03.2-ce-rc1

generate-stackbrew-library.sh
=> Slim down the number of aliases that release candidates get (A.B.C-ce-rcN, A.B-rc, test)

.appveyor.yml, update.sh
This is the follow-up companion to https://github.com/docker-library/docker/pull/75. :+1:
=> Add initial .appveyor.yml

17.06/dind/Dockerfile, 17.09/dind/Dockerfile, 17.10/dind/Dockerfile, Dockerfile-dind.template
=> Properly exclude "zfs" on arches it doesn't exist for

17.06/Dockerfile, 17.06/modprobe.sh, 17.09/Dockerfile, 17.09/modprobe.sh, 17.10/Dockerfile, 17.10/modprobe.sh, Dockerfile.template, modprobe.sh, update.sh
See https://twitter.com/lucabruno/status/902934379835662336
Closes #86
=> Add "ip link show" based modprobe tricks

.appveyor.yml, 17.09/windows/windowsservercore-1709/Dockerfile, 17.09/windows/windowsservercore-ltsc2016/Dockerfile, Dockerfile.template, generate-stackbrew-library.sh, update.sh
See also docker-library/hello-world#41.
=> Add explicit support for Windows Server 1709

18.06-rc/Dockerfile, 18.06/Dockerfile, update.sh
To address https://github.com/docker-library/docker/issues/121
=> Update to use alpine:3.8 as a base

18.09/Dockerfile, 19.03-rc/Dockerfile, update.sh
=> Update Alpine to 3.10

18.09-rc/dind/dockerd-entrypoint.sh, 18.09/dind/dockerd-entrypoint.sh, 19.03-rc/dind/dockerd-entrypoint.sh, 19.03/dind/dockerd-entrypoint.sh, dockerd-entrypoint.sh
=> Widen permissions on "client/key.pem" (especially for unprivileged usage)

19.03-rc/dind-rootless/Dockerfile, 19.03/dind-rootless/Dockerfile, Dockerfile-dind-rootless.template
Fix proxying UDP packets (https://github.com/rootless-containers/rootlesskit/issues/86)
Corresponds to https://github.com/moby/moby/pull/40317
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
=> update RootlessKit to v0.7.1

19.03-rc/Dockerfile, 19.03/Dockerfile, update.sh
=> Update to Alpine 3.11

19.03-rc/dind/dockerd-entrypoint.sh, 19.03/dind/dockerd-entrypoint.sh, dockerd-entrypoint.sh
=> Change 4196-bit key size to 4096 bits

19.03-rc/Dockerfile, 19.03/Dockerfile, update.sh
=> Update to Alpine 3.12

19.03-rc/dind-rootless/Dockerfile, 19.03/dind-rootless/Dockerfile, 20.10-rc/dind-rootless/Dockerfile, Dockerfile-dind-rootless.template
Upstream PR: https://github.com/moby/moby/pull/41634
=> bump up rootlesskit to v0.11.0

20.10-rc/dind-rootless/Dockerfile, 20.10/dind-rootless/Dockerfile, versions.json, versions.sh
=> Enable rootless-extras on arm64 for 20.10+

20.10-rc/Dockerfile, 20.10/Dockerfile, versions.json, versions.sh
Required for https://github.com/docker-library/docker/pull/265
=> update alpine to 3.14

20.10/Dockerfile, versions.json, versions.sh
resolve https://github.com/docker-library/docker/issues/338
=> update alpine to 3.15

20.10/windows/windowsservercore-ltsc2022/Dockerfile, versions.json, versions.sh
=> Add Windows Server LTSC 2022

20.10/Dockerfile, versions.json, versions.sh
See also https://alpinelinux.org/posts/Alpine-3.16.0-released.html.
=> Update to Alpine 3.16

20.10/cli/Dockerfile, 22.06-rc/cli/Dockerfile, Dockerfile-cli.template
See also https://alpinelinux.org/posts/Alpine-3.17.0-released.html.
=> Update to Alpine 3.17

20.10/cli/Dockerfile, 23.0/cli/Dockerfile, Dockerfile-cli.template
=> Ditch libc6-compat in 23+

24-rc/cli/Dockerfile, 24-rc/cli/docker-entrypoint.sh, 24-rc/cli/modprobe.sh, 24-rc/dind-rootless/Dockerfile, 24-rc/dind/Dockerfile, 24-rc/dind/dockerd-entrypoint.sh, 24-rc/git/Dockerfile, 24-rc/windows/windowsservercore-1809/Dockerfile, 24-rc/windows/windowsservercore-ltsc2022/Dockerfile, versions.json
=> Add 24.0.0-beta.1

25-rc/cli/Dockerfile, 25-rc/cli/docker-entrypoint.sh, 25-rc/cli/modprobe.sh, 25-rc/dind-rootless/Dockerfile, 25-rc/dind/Dockerfile, 25-rc/dind/dockerd-entrypoint.sh, 25-rc/git/Dockerfile, 25-rc/windows/windowsservercore-1809/Dockerfile, 25-rc/windows/windowsservercore-ltsc2022/Dockerfile, versions.json
https://github.com/moby/moby/releases/tag/v25.0.0-beta.1
=> Add 25.0.0-beta.1 pre-release

24/cli/Dockerfile, 25-rc/cli/Dockerfile, Dockerfile-cli.template
=> Add a "docker" group

26-rc/cli/Dockerfile, 26-rc/cli/docker-entrypoint.sh, 26-rc/cli/modprobe.sh, 26-rc/dind-rootless/Dockerfile, 26-rc/dind/Dockerfile, 26-rc/dind/dockerd-entrypoint.sh, 26-rc/windows/windowsservercore-1809/Dockerfile, 26-rc/windows/windowsservercore-ltsc2022/Dockerfile, versions.json
Modelled after #458 
See also https://github.com/moby/moby/releases/tag/v26.0.0-rc1
=> Add v26.0.0-rc1 pre-release

27-rc/cli/Dockerfile, 27-rc/cli/docker-entrypoint.sh, 27-rc/cli/modprobe.sh, 27-rc/dind-rootless/Dockerfile, 27-rc/dind/Dockerfile, 27-rc/dind/dockerd-entrypoint.sh, 27-rc/windows/windowsservercore-1809/Dockerfile, 27-rc/windows/windowsservercore-ltsc2022/Dockerfile, versions.json
Modelled after #484
See also https://github.com/moby/moby/releases/tag/v27.0.0-rc.1
=> Add v27.0.0-rc1 pre-release

28/cli/Dockerfile, 28/dind/Dockerfile, Dockerfile-cli.template, Dockerfile-dind.template
=> Update to Alpine 3.22
